[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python telegram_openai_assistant/main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
